
CREATE DATABASE CeilInn


CREATE TABLE Employee_Info (
	EmId INT PRIMARY KEY NOT NULLAUTO_INCREMENT,
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	Title VARCHAR(20) NOT NULL

);

CREATE TABLE Customer_Info (
	AccountNumber INT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	PhoneNumber VARCHAR(45) NOT NULL,
	EId INT(20), FOREIGN KEY(EId) REFERENCES Emergency_Contact(EId)
);


CREATE TABLE Emergency_Contact (
	EId INT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,	
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	PhoneNumber VARCHAR(45) NOT NULL
);

CREATE TABLE Status (
	SId INT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Status VARCHAR(45) NOT NULL
);

CREATE TABLE Bed (
	BId INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Type VARCHAR(45) NOT NULL
);

CREATE TABLE Type (
	TId INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Type VARCHAR(45) NOT NULL
);

CREATE TABLE Rate (
	RId INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Rate DOUBLE
);

CREATE TABLE Room (
  RoomNumber INT PRIMARY KEY NOT NULL,
  RId INT(5) NOT NULL, FOREIGN KEY(RId) REFERENCES Rate(RId),
  BId INT(5) NOT NULL, FOREIGN KEY(BId) REFERENCES Bed(BId),
  SId INT(3) NOT NULL, FOREIGN KEY(SId) REFERENCES Status(SId),
  TId INT(5) NOT NULL, FOREIGN KEY(TId) REFERENCES Type(TId)
);

CREATE TABLE Booking (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	EmId INT(10), FOREIGN KEY(EmId) REFERENCES Employee_Info(EmId),
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	AccountNumber INT(20) NOT NULL, FOREIGN KEY(AccountNumber) REFERENCES Customer_Info(AccountNumber),
	RoomNumber INT(20) NOT NULL, FOREIGN KEY(RoomNumber) REFERENCES Room(RoomNumber),
	Notes VARCHAR(200),
	RId INT(5) NOT NULL, FOREIGN KEY(RId) REFERENCES Rate(RId),
	PhoneCharge DOUBLE
);